// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ApexCharts() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-data=\"{\n        values: [45, 55, 75, 25, 45, 110],\n        labels: [&#39;Jan&#39;, &#39;Feb&#39;, &#39;Mar&#39;, &#39;Apr&#39;, &#39;May&#39;, &#39;June&#39;],\n        init() {\n            let chart = new ApexCharts(this.$refs.chart, this.options)\n\n            chart.render()\n\n            this.$watch(&#39;values&#39;, () =&gt; {\n                chart.updateOptions(this.options)\n            })\n        },\n        get options() {\n            return {\n                chart: { type: &#39;line&#39;, toolbar: false },\n                tooltip: {\n                    marker: false,\n                    y: {\n                        formatter(number) {\n                            return &#39;$&#39;+number\n                        }\n                    }\n                },\n                xaxis: { categories: this.labels },\n                series: [{\n                    name: &#39;Sales&#39;,\n                    data: this.values,\n                }],\n            }\n        }\n    }\" class=\"w-full\"><div x-ref=\"chart\" class=\"rounded-lg bg-white p-8\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
