// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Radio() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := ` Radio Group `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><div x-data=\"{\n        value: null,\n        select(option) { this.value = option },\n        isSelected(option) { return this.value === option },\n        hasRovingTabindex(option, el) {\n            // If this is the first option element and no option has been selected, make it focusable.\n            if (this.value === null &amp;&amp; Array.from(el.parentElement.children).indexOf(el) === 0) return true\n\n            return this.isSelected(option)\n        },\n        selectNext(e) {\n            let el = e.target\n            let siblings = Array.from(el.parentElement.children)\n            let index = siblings.indexOf(el)\n            let next = siblings[index === siblings.length - 1 ? 0 : index + 1]\n\n            next.click(); next.focus();\n        },\n        selectPrevious(e) {\n            let el = e.target\n            let siblings = Array.from(el.parentElement.children)\n            let index = siblings.indexOf(el)\n            let previous = siblings[index === 0 ? siblings.length - 1 : index - 1]\n\n            previous.click(); previous.focus();\n        },\n    }\" @keydown.down.stop.prevent=\"selectNext\" @keydown.right.stop.prevent=\"selectNext\" @keydown.up.stop.prevent=\"selectPrevious\" @keydown.left.stop.prevent=\"selectPrevious\" role=\"radiogroup\" :aria-labelledby=\"$id(&#39;radio-group-label&#39;)\" x-id=\"[&#39;radio-group-label&#39;]\" class=\"max-w-lg w-full\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := ` Radio Group Label `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><label :id=\"$id(&#39;radio-group-label&#39;)\" role=\"none\" class=\"hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `Backend framework: `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span x-text=\"value\"></span></label><div class=\"mt-4 space-y-2\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := ` Option `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><div x-data=\"{ option: &#39;laravel&#39; }\" @click=\"select(option)\" @keydown.enter.stop.prevent=\"select(option)\" @keydown.space.stop.prevent=\"select(option)\" :aria-checked=\"isSelected(option)\" :tabindex=\"hasRovingTabindex(option, $el) ? 0 : -1\" :aria-labelledby=\"$id(&#39;radio-option-label&#39;)\" :aria-describedby=\"$id(&#39;radio-option-description&#39;)\" x-id=\"[&#39;radio-option-label&#39;, &#39;radio-option-description&#39;]\" role=\"radio\" class=\"flex cursor-pointer rounded-md border border-gray-200 bg-white p-4 shadow\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := ` Checked Indicator `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><span :class=\"{ &#39;bg-cyan-400&#39;: isSelected(option) }\" class=\"mt-1 inline-flex h-4 w-4 shrink-0 items-center justify-center rounded-full border-2 border-white ring-1 ring-gray-600\" aria-hidden=\"true\"></span> <span class=\"ml-3\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := ` Primary Label `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><p :id=\"$id(&#39;radio-option-label&#39;)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var8 := `Laravel`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var9 := ` Secondary Information `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><span :id=\"$id(&#39;radio-option-description&#39;)\" class=\"mt-2 text-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var10 := `A PHP framework built by Taylor Otwell`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></span></div><div x-data=\"{ option: &#39;rails&#39; }\" @click=\"select(option)\" @keydown.enter.stop.prevent=\"select(option)\" @keydown.space.stop.prevent=\"select(option)\" :aria-checked=\"isSelected(option)\" :tabindex=\"hasRovingTabindex(option, $el) ? 0 : -1\" :aria-labelledby=\"$id(&#39;radio-option-label&#39;)\" :aria-describedby=\"$id(&#39;radio-option-description&#39;)\" x-id=\"[&#39;radio-option-label&#39;, &#39;radio-option-description&#39;]\" role=\"radio\" class=\"flex cursor-pointer rounded-md border border-gray-200 bg-white p-4 shadow\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var11 := ` Checked Indicator `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var11)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><span :class=\"{ &#39;bg-cyan-400&#39;: isSelected(option) }\" class=\"mt-1 inline-flex h-4 w-4 shrink-0 items-center justify-center rounded-full border-2 border-white ring-1 ring-gray-600\" aria-hidden=\"true\"></span> <span class=\"ml-3\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var12 := ` Primary Label `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var12)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><p :id=\"$id(&#39;radio-option-label&#39;)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var13 := `Rails`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var13)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var14 := ` Secondary Information `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var14)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><span :id=\"$id(&#39;radio-option-description&#39;)\" class=\"mt-2 text-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var15 := `A Ruby framework built by DHH`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></span></div><div x-data=\"{ option: &#39;phoenix&#39; }\" @click=\"select(option)\" @keydown.enter.stop.prevent=\"select(option)\" @keydown.space.stop.prevent=\"select(option)\" :aria-checked=\"isSelected(option)\" :tabindex=\"hasRovingTabindex(option, $el) ? 0 : -1\" :aria-labelledby=\"$id(&#39;radio-option-label&#39;)\" :aria-describedby=\"$id(&#39;radio-option-description&#39;)\" x-id=\"[&#39;radio-option-label&#39;, &#39;radio-option-description&#39;]\" role=\"radio\" class=\"flex cursor-pointer rounded-md border border-gray-200 bg-white p-4 shadow\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var16 := ` Checked Indicator `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><span :class=\"{ &#39;bg-cyan-400&#39;: isSelected(option) }\" class=\"mt-1 inline-flex h-4 w-4 shrink-0 items-center justify-center rounded-full border-2 border-white ring-1 ring-gray-600\" aria-hidden=\"true\"></span> <span class=\"ml-3\"><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var17 := ` Primary Label `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var17)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><p :id=\"$id(&#39;radio-option-label&#39;)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var18 := `Phoenix`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var18)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var19 := ` Secondary Information `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var19)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><span :id=\"$id(&#39;radio-option-description&#39;)\" class=\"mt-2 text-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var20 := `An Elixir framework built by Chris McCord`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var20)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
